# Generated by Django 4.2.6 on 2023-10-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mobile',
        ),
    ]
