# Generated by Django 4.2.6 on 2023-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=9)),
                ('semester', models.PositiveIntegerField()),
                ('excel_file', models.FileField(upload_to='static/class_files/')),
                ('session', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous')], default='current', max_length=10)),
            ],
        ),
    ]
