# Generated by Django 4.2.6 on 2023-10-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
